version: '3'
services:
 api:
  container_name: api_nodejs
  restart: always
  image: edwinwalela/cwsk-restapi:v1
  ports:
   - '5000:5000'
 vue:
  container_name: frontend_vue
  restart: always
  image: edwinwalela/cwsk-vue-frontend:v1
  ports:
   - '80:8080'